### ISSUE TITLE
MIDI Out on Android

### ISSUE THREAD

**Issue by nicopan** [monkeyswarm/MobMuPlat#39]
Hi, I'm trying to use MobMuPlat on Android 6 in order to send MIDI CC to a softsynth on my laptop.
I connect the Android device to my laptop, choosing the "MIDI device" USB option, but I don't see any device in the "Audio & MIDI" screen of MobMuPlat, even refreshing it.
Is that type of connection supported?
Thanks!

**Comment by monkeyswarm** [comment]
No. That USB configuration is for connecting MIDI devices _to_ the Android device, not having your Android device show up as a MIDI device on another host (laptop). 

I've never had to use that option, since on my Android devices, the MIDI devices show up fine without having to switch the configuration from the default.

To use your Android device as a controller for your softsynth, you'll probably have to convert your MIDI to some other format (e.g. OSC messages or raw bytes), send it via a network connection to your laptop, unpack it there and re-pack it as MIDI messages, and send locally to your softsynth. That is all doable with Pd (and MobMuPlat). Or you'll have to buy some hardware (which shows up as a MIDI OUT device for MobMuPlat, and a MIDI IN device for your laptop) that can send MIDI between two hosts.
