### ISSUE TITLE
getNetwork is not receiving well messages.

### ISSUE THREAD

**Issue by MarioMey** [monkeyswarm/MobMuPlat#6]
Please, do this:

- Load bug-label.zip into a tablet (I tried in Android 4.0.3, Samsung Galaxy Tab 2 10')
- (check bug-label.pd to see what's inside)
- Load label-0.46.pd into Pd_Vanilla 0.46 or...
- Load label-0.44.pd into Pd Extended 0.44.

There're 2 labels: /1/terminal and /meh-terminal in other zip file.

- Send some messages using messages.
- Check the MobMuPlat interface...
- Check the Console.

My results: some weird messages arrives in the Labels and in MobMuPlat Console. Numbers instead of words, float point numbers instead of a simple "1", shortened words...
[bug-label.zip](https://github.com/monkeyswarm/MobMuPlat/files/108912/bug-label.zip)
[test-fila-vanilla-extended.zip](https://github.com/monkeyswarm/MobMuPlat/files/108917/test-fila-vanilla-extended.zip)

**Comment by MarioMey** [comment]
[test-fila-vanilla-extended.zip](https://github.com/monkeyswarm/MobMuPlat/files/108916/test-fila-vanilla-extended.zip)

**Comment by monkeyswarm** [comment]
Hi,
You are sending and receiving from port numbers that MobMuPlat is not listening or sending on. (I don't know why you are getting anything at all in the console...)
The default receive port for MobMuPlat is 54322, default send is 54321.
Change your "connect" message (to netsend) to use 54322, and your "listen" message (to netreceive) to use 54321. I did that and it worked for me.
Let me know if that fixes it for you.

**Comment by MarioMey** [comment]
Obviously and previously, I configured MobMuPlat to listen and send to 8000 and 9000 ports (so, I didn't have to change my patch that I was using with TouchOSC).

Do you mean that MobMuPlat doesn't work with other ports? That I must use 543421 and 54322?

Anyway, after changing ports to 54321 and 54322, I did some tests... and I did not have good results. It seems that the messages are arriving wrong and/or mixed. Look at this log:
![screenshot](https://cloud.githubusercontent.com/assets/4954109/12679470/2d626f70-c683-11e5-8245-09fac556e489.png)

Using label-0.46.pd:
- I clicked in [list papa mama meme( and [symbol papamamababa( several times... (for my mistake, it arrives to the toggle, but it doesn't matter here, it's just a test).
- I changed address with [set meh-terminal(... and look what happened: instead of "papa mama meme", it arrives "papa meme".
- I changed to /myToggle and send it 0 and 1, it worked Ok.
- I changed to /1/terminal and "papapapamamababa" arrived (first element in the list concatenated with the other message).
-...
- Then, I tried to set the toggle by sending [set 1( and it arrives: "set 2.7908e+29".

There's something wrong....

**Comment by MarioMey** [comment]
Is there any other way to build the messages inside PureData before send them?
Anyway, the problem is by using Vanilla AND Extended... and we know that they have different ways to use network to send messages... in both versions it is working wrong. Maybe the Android version? The tablet itself? (with TouchOSC and Pd-Extended, any message arrives well).

**Comment by monkeyswarm** [comment]
You are correct, you can also just change the port numbers in network settings. Most people forget to do that. Note that I also had to change the mobmuplat output destination (to something other than multicast), otherwise I would get an infinite loop.

I get the expected results, see below. I do not get any of your bugs. I am using a Nexus 6 running Android 5.1.1. 
Perhaps the older Android version does not handle network messaging correctly. Please try a different android device/OS version and/or wifi router. I will try to find a 4.0.2 device and check.

![screenshot_2016-01-29-08-36-19 1](https://cloud.githubusercontent.com/assets/1235083/12681679/9d1f8f06-c664-11e5-9c8f-7e3c94b43840.png)

**Comment by MarioMey** [comment]
Uh, man... this is the worst result that I could obtain by debugging a bug... realize that the problem is in my tablet.

I tested the file with my LG Leon (Android 5.0.1) and it works like a charm. But I can't  just throw away my tablet (*) and buy another one.

Is there anything we can do to fix this version-related bug?

(*): this tablet is an old one, but it costs AR$ 4.000, here (used). My country's minimum wage is AR$ 6.000.

**Comment by MarioMey** [comment]
(Argentina)

**Comment by MarioMey** [comment]
I tried PdDroidParty and, after some hours... finally, I can send messages using [netsend -u - b] / [netreceive -u -b] and see them printed with "adb logcat". They arrive pretty OK.

How could we debug MobMuPlat to work correctly in this Android version? It's a bit messy to make the interface with PDP... (I like better MMP).

**Comment by monkeyswarm** [comment]
Ok...hopefully I have a solution. I am emailing you directly an APK, please try it out with using [netsend] and [netreceive].

Background: netsend and netreceive actually do work in MobMuPlat, but a) can cause some instability e.g. the patch closes without releasing the ports (I've only seen that on iOS so far) and b) I like handling the networking at the app layer so that I can add networking protocols to it. c) Current android version of MMP doesn't have oscformat and oscparse....but I've just added them, so the next update will.

I've added oscformat and oscparse to a build and sent it to you. I've tested it on recent OS/device, and on a Galaxy nexus running 4.0.4, and both work.

I'll still investigate why 4.0.4 has network issues at the Android network level. (netsend/receive bypass the android networking level to interact with sockets directly, so they may avoid whatever Android bugs were causing the initial issue), but that's going to be lower priority and probably not something I can work around.

**Comment by MarioMey** [comment]
Oh, man... I really love open source software people/comunity... I love you!
I just wake up and receive this mail, I'm very glad you are helping me.

However... the APK could not be installed. It says

**Comment by MarioMey** [comment]
Here is the

**Comment by monkeyswarm** [comment]
The apk I sent you was unsigned. I'm sending you a signed one now.

**Comment by MarioMey** [comment]
Yes, it could be installed. And it really works!

Now... I should ask you something (it is this issue related, but not a bug, so, if you want, we remove this and go on by mail).

As I won't use [receive fromNetwork] and I will use [oscparse], I'm getting the address and the data all mixed in a list. So, I can't send it directly to [send toGUI]. And, as oscparse help file says:

... *Also, no attempt is made here to clearly distinguish between the OSC address (symbols) and the following data* ...

... this means that I won't can make a simple patch to pass the messages to the GUI, as it is in the text patch uploaded in this issue. For the moment, I'm thinking in this way to do it (automatically):

- Using a known subfolder lenght: for example 3 (I was using 3). So, the addresses will always be /1/a/foo, /2/b/too, etc. Then, using first 3 elements in the list, I could make the address by joining them with "/" and then add the data to it, to send the new list to [send toGUI]. (I will research how to concatenate them...)

Are you thinking in another way to do it?

Thank you very much.

**Comment by MarioMey** [comment]
All my addresses are two elements long. So:
![pantallazo-1](https://cloud.githubusercontent.com/assets/4954109/12789918/94bd2238-ca7e-11e5-8417-885879dd5c96.png)

This is the only set of "boxes" that I use to receive messages. It works perfect.

I don't know if this bug report could be closed... because the "receive fromNetwork" still don't work in this Android version, but the netreceive does the trick.

**Comment by monkeyswarm** [comment]
pd vanilla does not currently have a good way to route or split an OSC address like "/foo/bar/baz", which is why the built-in oscparse object splits it into multiple symbols in a list (without slashes). You can use that functionality in this case to take the MobMuPlat-style address ("/foo/bar") and turn it into a list ("foo bar"). Or you can break up the MMP-style address into ascii and manually parse it on the slash character.
![screen shot 2016-06-24 at 8 29 02 am](https://cloud.githubusercontent.com/assets/1235083/16342208/c80908ba-39e5-11e6-8c3e-22edeca28d36.png)

[charsplit.txt](https://github.com/monkeyswarm/MobMuPlat/files/331999/charsplit.txt)

**Comment by MarioMey** [comment]
I finally didn't need to break apart the address... but I had made this patch to do it. It is "there", unconnected.

![pantallazo-address2address - -home-mario-circo3d-work-android-mobmuplat](https://cloud.githubusercontent.com/assets/4954109/16347560/bd9a0f44-3a23-11e6-85fa-7de346fa5047.png)

Some day, I'll try your patch... maybe it is simplier than mine!

**Comment by MarioMey** [comment]
For the next release, don't forget to leave netsend and netreceive...

**Comment by monkeyswarm** [comment]
what do you mean by "leave" netsend and netreceive? Those objects should be usable in the current release.

**Comment by MarioMey** [comment]
I remember that netsend and netreceive weren't in the release I had downloaded. So, you built me a version that included those objects. I don't know if you modified trunk or a branch.

Since that moment, I didn't check for new versions...

**Comment by monkeyswarm** [comment]
Those objects should be in the current MobMuPlat version. Let me know if they are not.

**Comment by MarioMey** [comment]
I don't have time to test it right now... I trust you!
