### ISSUE TITLE
network menu closes the app

### ISSUE THREAD

**Issue by JRSV** [monkeyswarm/MobMuPlat#65]
I have mobmuplat in different devices and they work great, except for an Android phone which just closes the app when opening network tab in the menu. Huawei honor view 20 running android 10. Please advise on how to troubleshoot, debug, etc.

**Comment by monkeyswarm** [comment]
Behavior confirmed on recent android OS, looks like a dependency is no longer supported.

====
03-23 13:16:00.284 31501 31501 E InputEventReceiver: Exception dispatching input event.
03-23 13:16:00.284 31501 31501 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/util/InetAddressUtils;
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.iglesiaintermedia.mobmuplat.NetworkController.getIPAddress(NetworkController.java:235)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.iglesiaintermedia.mobmuplat.NetworkFragment$MultiDirectFragment.onCreateView(NetworkFragment.java:181)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2361)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:784)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.iglesiaintermedia.mobmuplat.MainActivity.launchFragment(MainActivity.java:1147)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.iglesiaintermedia.mobmuplat.MainActivity.onOptionsItemSelected(MainActivity.java:1173)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.app.Activity.onMenuItemSelected(Activity.java:4156)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1255)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.DropDownListView.onTouchEvent(DropDownListView.java:116)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:13953)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
03-23 13:16:00.287 31501 31501 E MessageQueue-JNI: 	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupW
03-23 13:16:00.287 31501 31501 D AndroidRuntime: Shutting down VM
03-23 13:16:00.289 31501 31501 E AndroidRuntime: FATAL EXCEPTION: main
03-23 13:16:00.289 31501 31501 E AndroidRuntime: Process: com.iglesiaintermedia.mobmuplat, PID: 31501
03-23 13:16:00.289 31501 31501 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/util/InetAddressUtils;
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.iglesiaintermedia.mobmuplat.NetworkController.getIPAddress(NetworkController.java:235)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.iglesiaintermedia.mobmuplat.NetworkFragment$MultiDirectFragment.onCreateView(NetworkFragment.java:181)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2361)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:784)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.iglesiaintermedia.mobmuplat.MainActivity.launchFragment(MainActivity.java:1147)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.iglesiaintermedia.mobmuplat.MainActivity.onOptionsItemSelected(MainActivity.java:1173)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:4156)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1255)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.widget.DropDownListView.onTouchEvent(DropDownListView.java:116)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:13953)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
03-23 13:16:00.289 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2554)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14212)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:336)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:174)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.conn.util.InetAddressUtils" on path: DexPathList[[zip file "/data/app/com.iglesiaintermedia.mobmuplat-2wUnU1yZT6sgT0tdbNYaGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.iglesiaintermedia.mobmuplat-2wUnU1yZT6sgT0tdbNYaGw==/lib/arm64, /data/app/com.iglesiaintermedia.mobmuplat-2wUnU1yZT6sgT0tdbNYaGw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-23 13:16:00.290 31501 31501 E AndroidRuntime: 	... 73 more
03-23 13:16:00.294  1540 31757 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

**Comment by JRSV** [comment]
Great!! already fixed, Thanks for your work
